version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:4173"

  backend:
    build: ./backend
    depends_on:
      - dynamodb
    volumes:
      - storage_volume:/storage
    ports:
      - "8000:8000"

  dynamodb:
    command: "-jar DynamoDBLocal.jar -disableTelemetry -sharedDb"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8080:8000"

volumes:
  storage_volume:
