version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:4173"

  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:
